# Generated by Django 4.1.7 on 2023-03-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='posts_images/facebook')),
                ('url', models.URLField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('last_retrieve', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='posts_images/instagram')),
                ('url', models.URLField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('last_retrieve', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('profile_image', models.URLField(max_length=500)),
                ('tweet_text', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='posts_images/twitter')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('last_retrieve', models.DateField(auto_now=True)),
            ],
        ),
    ]
