# Generated by Django 4.1.7 on 2023-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0002_tweetkeyword_youtubekeyword_tweet_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='display_name',
            field=models.CharField(default='deletar', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.CharField(max_length=280),
        ),
        migrations.DeleteModel(
            name='TweetKeyword',
        ),
        migrations.AddField(
            model_name='tweet',
            name='keyword',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
