# Generated by Django 4.1.7 on 2023-03-29 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0003_tweet_display_name_remove_tweet_keyword_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeKeyword',
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='post_date',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='last_retrieve',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='channel_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='description_excerpt',
            field=models.CharField(default='6009-07-24', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='keyword',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='profile_image',
            field=models.URLField(default='2', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='thumbnail',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
