# Generated by Django 4.1.7 on 2023-04-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0004_delete_youtubekeyword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagrampost',
            old_name='url',
            new_name='media_url',
        ),
        migrations.RenameField(
            model_name='instagrampost',
            old_name='post_date',
            new_name='post_time',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instagrampost',
            name='last_retrieve',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='caption',
            field=models.CharField(default='dale, dale, Grêmio', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='comments_count',
            field=models.CharField(default='dale, dale, Grêmio', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='ig_display_name',
            field=models.CharField(default='dale, dale, Grêmio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='ig_username',
            field=models.CharField(default='Dale, dale, grêmio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='likes_count',
            field=models.CharField(default='dale, dale, grêmio', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='media_type',
            field=models.CharField(default='dale, dale, grêmio', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(default='dale, dale, grêmio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='profile_picture',
            field=models.URLField(default='dale, dale, grêmio'),
            preserve_default=False,
        ),
    ]
