# Generated by Django 4.1.7 on 2023-04-14 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retriever', '0007_remove_instagrampost_media_url_instagrampostimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideoKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='FacebookPost',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='post_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='upload_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='youtubevideokeyword',
            name='yt_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retriever.youtubevideo'),
        ),
        migrations.AddField(
            model_name='tweetkeyword',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retriever.tweet'),
        ),
    ]
