version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: nodata_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23061999Mj
    volumes:
      - ./data/db:/var/lib/postgresql/data
