version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    # ports:
    #   - '5432:5432'
    environment:
      - POSTGRES_DB=postgres_nodata
      - POSTGRES_USER=nodata_user
      - POSTGRES_PASSWORD=232323
  web: 
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres_nodata
      - POSTGRES_USER=nodata_user
      - POSTGRES_PASSWORD=232323
    depends_on:
      - db

    
    
