version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres_nodata
      - POSTGRES_USER=nodata_user
      - POSTGRES_PASSWORD=232323
  
  gunicorn_web: 
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - static_data:/app/staticfiles
      - upload_data:/app/uploads
    ports: 
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres_nodata
      - POSTGRES_USER=nodata_user
      - POSTGRES_PASSWORD=232323
    depends_on:
      - db
  
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: on-failure
    ports:
      - "80:80" 
    volumes:
      - static_data:/static_data
      - upload_data:/upload_data
    depends_on:
      - gunicorn_web

volumes:
  static_data:
  upload_data: