version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_nodata
      - POSTGRES_USER=nodata_user
      - POSTGRES_PASSWORD=232323
  
  gunicorn_web: 
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres_nodata
      - POSTGRES_USER=nodata_user
      - POSTGRES_PASSWORD=232323
    depends_on:
      - db
  
  nginx: 
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/static
      - ./uploads:/uploads
    ports:
      - "80:80" 
    depends_on:
      - gunicorn_web