# Generated by Django 4.2 on 2023-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorin', '0004_post_post_slug_profile_friends_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post_pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date_post',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
