# Generated by Django 4.2 on 2023-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorin', '0006_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(max_length=15, unique=True),
        ),
    ]
