# Generated by Django 4.2 on 2023-07-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorin', '0007_alter_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='dorin.profile'),
        ),
    ]
