# Generated by Django 4.2 on 2023-07-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorin', '0008_alter_post_parent_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dorin.post'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dorin.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dorin.profile'),
        ),
    ]
