# Generated by Django 4.2 on 2023-07-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorin', '0009_alter_comment_parent_post_alter_likes_parent_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication_date_comment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
