# Generated by Django 4.2 on 2023-08-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorin', '0010_alter_comment_publication_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='custom_slug_profile',
            field=models.SlugField(max_length=15, unique=True),
        ),
    ]
