# Generated by Django 4.2 on 2023-08-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorin', '0011_alter_profile_custom_slug_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
